spring:
  datasource:
    url: jdbc:mariadb://218.148.64.128:3306/webtoondb
    username: chihwan
    password: 123456
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  profiles:
    include:
      - oauth
      - jwt

  servlet:
    multipart:
      max-request-size: 30MB
      max-file-size: 10MB

com:
  dev:
    upload:
      path: upload