spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 219398962369-qtev3ifv20a4qp5u8js0ccsfodtb10fk.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            authorization-grant-type: authorization_code
            scope: profile, email
            client-name: google

          naver:
            client-id: 3R51Sv_8YMwxSWWF2vb0
            client-secret: VGWvOV9UlM
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: name, email
            client-name: Naver

          kakao:
            client-id: 133d7fa2aed23a0bd2721f1f49bc82af
            client-secret: 6aUPvke73nju00QpHihzqcopslg1L6v8
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope: profile_nickname
            client-name: Kakao

        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

