spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/webtoondb
    username: root
    password: 123456
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
